testy_homepage
kamamenszu/Mercury_tours pull request #1
Opened 2019-01-07 21:04 UTC by kamamenszu

Hej, zrobiłam spec dla testowej strony Mercury_tours, która była podana w kilku zadaniach z selenium tutorials.

2019-01-09 08:32 UTC, jacekokrojek requested changes

2019-01-09 08:32 UTC, jacekokrojek commented on home.spec.js
> +		expect(homePage.getText()).toEqual("© 2005, Mercury Interactive (v. 011003-1.01-058)");
I think that getText is not enough meaningful name for the function. Please change it.

2019-01-09 08:32 UTC, jacekokrojek commented on home.spec.js
> +		expect(homePage.visableLogo()).toBe(true);
By convention if funtion return boolean value it should be named isXXX.

2019-01-09 08:32 UTC, jacekokrojek commented on home.spec.js
> +		expect(homePage.getLeftMenuAtIdx(2).getText()).toBe("Hotels");
Can you change this test so it verifies all menu items in both menus. Please create a function that returns all menu elements for each menu.

2019-01-09 08:32 UTC, jacekokrojek commented on pages/home.js
> +  /*this.clickArrow = function() {
Please remove commented text

2019-01-09 10:12 UTC, kamamenszu commented
I've changed cases You asked me.

2019-01-09 13:12 UTC, kamamenszu commented
I've changed spec for menu, using map.function.

2019-01-10 19:10 UTC, jacekokrojek approved these changes

2019-01-11 08:46 UTC, merged